dataName = "‹ãB“S“¹";
dataFileName = "kyutetsu.js";
MAXLINE = 10;

stationList.addToStaList(new Station("•Ÿ‰ª”Ž‘½", "Fukuoka-Hakata", "KA01"));
stationList.addToStaList(new Station("“Œ“ß‰Ï", "Higashi-naka", "KA02"));
stationList.addToStaList(new Station("”Â•t", "Itazuke", "KA03"));
stationList.addToStaList(new Station("ˆä‘Š“c", "Isoda", "KA04"));
stationList.addToStaList(new Station("t“ú", "Kasuga", "KA05"));
stationList.addToStaList(new Station("”’–ØŒ´", "Shirakibaru", "KA06"));
stationList.addToStaList(new Station("‘å—˜", "Ori", "KA07"));
stationList.addToStaList(new Station("‹g¼", "Yoshimatsu", "KA08"));
stationList.addToStaList(new Station("“s•{˜O", "Tofuro", "KA09"));
stationList.addToStaList(new Station("“ñ“úŽs", "Futsukaichi", "KA10"));
stationList.addToStaList(new Station("“ì“ñ“úŽs", "Minami-Futsukaichi", "KA11"));
stationList.addToStaList(new Station("j ", "Harisuri", "KA12"));
stationList.addToStaList(new Station("‰i‰ª", "Nagaoka", "KA13"));
stationList.addToStaList(new Station("Žá]", "Wakae", "KA14"));
stationList.addToStaList(new Station("Œ´“c", "Haruda", "KA15"));
stationList.addToStaList(new Station("”ü‚µ‚ª‹u", "Utsukushigaoka", "KA16"));
stationList.addToStaList(new Station("‰¡ŒG", "Yokokuma", "KA17"));
stationList.addToStaList(new Station("ŽO‘ò", "Misawa", "KA18"));
stationList.addToStaList(new Station("“Œ–ì", "Higashino", "KA19"));
stationList.addToStaList(new Station("¬ŒS", "Ogori", "KA20"));
stationList.addToStaList(new Station("•Ÿ“¶", "Fukudo", "KA21"));
stationList.addToStaList(new Station("‹{ƒmw", "Miyanojin", "KA22"));
stationList.addToStaList(new Station("‹v—¯•Ä", "Kurume", "KA23"));
stationList.addToStaList(new Station("’Ã•Ÿ", "Tsufuku", "KA24"));
stationList.addToStaList(new Station("ã’Ã", "Kamitsu", "KA25"));
stationList.addToStaList(new Station("r–Ø", "Araki", "KA26"));
stationList.addToStaList(new Station("ˆêð", "Ichijo", "KA27"));
stationList.addToStaList(new Station("‘ ”", "Kurakazu", "KA28"));
stationList.addToStaList(new Station("ŒF–ì", "Kumano", "KA29"));
stationList.addToStaList(new Station("‰HŒ¢’Ë", "Hainuzuka", "KA30"));
stationList.addToStaList(new Station("˜aò", "Izumi", "KA31"));
stationList.addToStaList(new Station("…“c", "Mizuta", "KA32"));
stationList.addToStaList(new Station("”ö“‡", "Ojima", "KA33"));
stationList.addToStaList(new Station("–{‹½", "Hongo", "KA34"));
stationList.addToStaList(new Station("£‚", "Sedaka", "KA35"));
stationList.addToStaList(new Station("‘å]", "Oe", "KA36"));
stationList.addToStaList(new Station("ŠC’Ã", "Kaizu", "KA37"));
stationList.addToStaList(new Station("“cK", "Tajiri", "KA38"));
stationList.addToStaList(new Station("’}Œã‹{è", "Chikugo-Miyazaki", "KA39"));
stationList.addToStaList(new Station("‘q‰i", "Kuranaga", "KA40"));
stationList.addToStaList(new Station("’}ŒãŠÃ–Ø", "Chikugo-Amagi", "KA41"));
stationList.addToStaList(new Station("‘å–´“c”’ì", "Omuta-Shirakawa", "KA42"));
stationList.addToStaList(new Station("‘å–´“c", "Omuta", "KA43"));
stationList.addToStaList(new Station("éj”n", "Hayame", "KA44"));
stationList.addToStaList(new Station("‘å–´“c‰Pˆä", "Omuta-Usui", "KA45"));
stationList.addToStaList(new Station("ˆäŽè", "Ide", "KA46"));
stationList.addToStaList(new Station("r”ö", "Arao", "KA47"));
stationList.addToStaList(new Station("•{–{", "Fumoto", "KA48"));
stationList.addToStaList(new Station("‰ÔŽR", "Kanayama", "KA49"));
stationList.addToStaList(new Station("¼ÆŽ›", "Saishoji", "KA50"));
stationList.addToStaList(new Station("’z’n", "Tsukiji", "KA51"));
stationList.addToStaList(new Station("‹Ê–¼", "Tamana", "KA52"));
stationList.addToStaList(new Station("‘å‘q", "Okura", "KA53"));
stationList.addToStaList(new Station("Ž›“c", "Terada", "KA54"));
stationList.addToStaList(new Station("ˆî²", "Inasa", "KA55"));
stationList.addToStaList(new Station("–Ø—t", "Kiha", "KA56"));
stationList.addToStaList(new Station("A–Ø", "Ueki", "KA57"));
stationList.addToStaList(new Station("Œ¥ì", "Suzurikawa", "KA58"));
stationList.addToStaList(new Station("¼—¢", "Nishisato", "KA59"));
stationList.addToStaList(new Station("“¿‰¤", "Tokuou", "KA60"));
stationList.addToStaList(new Station("”ìŒã’r“c", "Higo-Ikeda", "KA61"));
stationList.addToStaList(new Station("“‡è", "Shimazaki", "KA62"));
stationList.addToStaList(new Station("ŒF–{", "Kumamoto", "KA63"));

var Kumamoto = new Line("ŒF–{–{ü", 0, false, "#f23f36");
var KAstation = new Array();
var KAkillo = new Array();

KAstation.push(stationList.searchFromNumberling("KA01", "KA02", "KA03", "KA04", "KA05", "KA06", "KA07", "KA08", "KA09", "KA10", "KA11", "KA12", "KA13", "KA14", "KA15", "KA16", "KA17", "KA18", "KA19", "KA20", "KA21", "KA22", "KA23", "KA24", "KA25", "KA26", "KA27", "KA28", "KA29", "KA30", "KA31", "KA32", "KA33", "KA34", "KA35", "KA36", "KA37", "KA38", "KA39", "KA40", "KA41", "KA42", "KA43", "KA44", "KA45", "KA46", "KA47", "KA48", "KA49", "KA50", "KA51", "KA52", "KA53", "KA54", "KA55", "KA56", "KA57", "KA58", "KA59", "KA60", "KA61", "KA62", "KA63"));

KAstation.push(stationList.searchFromNumberling("KA01"));
KAkillo.push(2.0);
KAstation.push(stationList.searchFromNumberling("KA02"));
KAkillo.push(1.5);
KAstation.push(stationList.searchFromNumberling("KA03"));
KAkillo.push(2.0);
KAstation.push(stationList.searchFromNumberling("KA04"));
KAkillo.push(1.6);
KAstation.push(stationList.searchFromNumberling("KA05"));
KAkillo.push(1.4);
KAstation.push(stationList.searchFromNumberling("KA06"));
KAkillo.push(1.1);
KAstation.push(stationList.searchFromNumberling("KA07"));
KAkillo.push(1.0);
KAstation.push(stationList.searchFromNumberling("KA08"));
KAkillo.push(1.2);
KAstation.push(stationList.searchFromNumberling("KA09"));
KAkillo.push(1.1);
KAstation.push(stationList.searchFromNumberling("KA10"));
KAkillo.push(1.1);
KAstation.push(stationList.searchFromNumberling("KA11"));
KAkillo.push(1.2);
KAstation.push(stationList.searchFromNumberling("KA12"));
KAkillo.push(1.4);
KAstation.push(stationList.searchFromNumberling("KA13"));
KAkillo.push(1.9);
KAstation.push(stationList.searchFromNumberling("KA14"));
KAkillo.push(0.9);
KAstation.push(stationList.searchFromNumberling("KA15"));
KAkillo.push(0.8);
KAstation.push(stationList.searchFromNumberling("KA16"));
KAkillo.push(1.3);
KAstation.push(stationList.searchFromNumberling("KA17"));
KAkillo.push(1.4);
KAstation.push(stationList.searchFromNumberling("KA18"));
KAkillo.push(1.2);
KAstation.push(stationList.searchFromNumberling("KA19"));
KAkillo.push(1.4);
KAstation.push(stationList.searchFromNumberling("KA20"));
KAkillo.push(1.9);
KAstation.push(stationList.searchFromNumberling("KA21"));
KAkillo.push(5.4);
KAstation.push(stationList.searchFromNumberling("KA22"));
KAkillo.push(2.5);
KAstation.push(stationList.searchFromNumberling("KA23"));
KAkillo.push(1.3);
KAstation.push(stationList.searchFromNumberling("KA24"));
KAkillo.push(1.9);
KAstation.push(stationList.searchFromNumberling("KA25"));
KAkillo.push(1.6);
KAstation.push(stationList.searchFromNumberling("KA26"));
KAkillo.push(2.1);
KAstation.push(stationList.searchFromNumberling("KA27"));
KAkillo.push(1.0);
KAstation.push(stationList.searchFromNumberling("KA28"));
KAkillo.push(1.7);
KAstation.push(stationList.searchFromNumberling("KA29"));
KAkillo.push(1.2);
KAstation.push(stationList.searchFromNumberling("KA30"));
KAkillo.push(1.1);
KAstation.push(stationList.searchFromNumberling("KA31"));
KAkillo.push(1.1);
KAstation.push(stationList.searchFromNumberling("KA32"));
KAkillo.push(1.4);
KAstation.push(stationList.searchFromNumberling("KA33"));
KAkillo.push(2.0);
KAstation.push(stationList.searchFromNumberling("KA34"));
KAkillo.push(1.2);
KAstation.push(stationList.searchFromNumberling("KA35"));
KAkillo.push(1.3);
KAstation.push(stationList.searchFromNumberling("KA36"));
KAkillo.push(2.0);
KAstation.push(stationList.searchFromNumberling("KA37"));
KAkillo.push(1.9);
KAstation.push(stationList.searchFromNumberling("KA38"));
KAkillo.push(3.0);
KAstation.push(stationList.searchFromNumberling("KA39"));
KAkillo.push(1.6);
KAstation.push(stationList.searchFromNumberling("KA40"));
KAkillo.push(1.0);
KAstation.push(stationList.searchFromNumberling("KA41"));
KAkillo.push(2.0);
KAstation.push(stationList.searchFromNumberling("KA42"));
KAkillo.push(1.6);
KAstation.push(stationList.searchFromNumberling("KA43"));
KAkillo.push(1.4);
KAstation.push(stationList.searchFromNumberling("KA44"));
KAkillo.push(1.2);
KAstation.push(stationList.searchFromNumberling("KA45"));
KAkillo.push(1.3);
KAstation.push(stationList.searchFromNumberling("KA46"));
KAkillo.push(1.4);
KAstation.push(stationList.searchFromNumberling("KA47"));
KAkillo.push(1.7);
KAstation.push(stationList.searchFromNumberling("KA48"));
KAkillo.push(2.4);
KAstation.push(stationList.searchFromNumberling("KA49"));
KAkillo.push(2.3);
KAstation.push(stationList.searchFromNumberling("KA50"));
KAkillo.push(2.1);
KAstation.push(stationList.searchFromNumberling("KA51"));
KAkillo.push(1.7);
KAstation.push(stationList.searchFromNumberling("KA52"));
KAkillo.push(2.8);
KAstation.push(stationList.searchFromNumberling("KA53"));
KAkillo.push(1.5);
KAstation.push(stationList.searchFromNumberling("KA54"));
KAkillo.push(1.6);
KAstation.push(stationList.searchFromNumberling("KA55"));
KAkillo.push(1.8);
KAstation.push(stationList.searchFromNumberling("KA56"));
KAkillo.push(5.8);
KAstation.push(stationList.searchFromNumberling("KA57"));
KAkillo.push(2.9);
KAstation.push(stationList.searchFromNumberling("KA58"));
KAkillo.push(1.3);
KAstation.push(stationList.searchFromNumberling("KA59"));
KAkillo.push(1.7);
KAstation.push(stationList.searchFromNumberling("KA60"));
KAkillo.push(1.4);
KAstation.push(stationList.searchFromNumberling("KA61"));
KAkillo.push(1.9);
KAstation.push(stationList.searchFromNumberling("KA62"));
KAkillo.push(0.9);
KAstation.push(stationList.searchFromNumberling("KA63"));

Kumamoto.setSta(KAstation, KAkillo);
lines.push(Kumamoto);

var Farerule = new FareTable(1)

var Farerule.fareRows.push(new FareRow(1, 3, 150));
var Farerule.fareRows.push(new FareRow(4, 6, 210));
var Farerule.fareRows.push(new FareRow(7, 9, 260));
var Farerule.fareRows.push(new FareRow(10, 12, 310));
var Farerule.fareRows.push(new FareRow(13, 15, 380));
var Farerule.fareRows.push(new FareRow(18, 22, 440));
var Farerule.fareRows.push(new FareRow(23, 26, 510));
var Farerule.fareRows.push(new FareRow(27, 30, 590));
var Farerule.fareRows.push(new FareRow(31, 35, 680));
var Farerule.fareRows.push(new FareRow(36, 40, 760));
var Farerule.fareRows.push(new FareRow(41, 45, 830));
var Farerule.fareRows.push(new FareRow(46, 50, 920));
var Farerule.fareRows.push(new FareRow(51, 60, 1040));
var Farerule.fareRows.push(new FareRow(61, 70, 1180));
var Farerule.fareRows.push(new FareRow(71, 80, 1320));
var Farerule.fareRows.push(new FareRow(81, 90, 1490));
var Farerule.fareRows.push(new FareRow(91, 100, 1650));
var Farerule.fareRows.push(new FareRow(101, 120, 1830));
var Farerule.fareRows.push(new FareRow(121, 140, 1980));
var Farerule.fareRows.push(new FareRow(141, 160, 2310));
var Farerule.fareRows.push(new FareRow(161, 180, 2520));
var Farerule.fareRows.push(new FareRow(181, 200, 2870));
